different args for mktemp on darwin

diff --git a/sh/gpg-backup b/sh/gpg-backup
--- a/sh/gpg-backup
+++ b/sh/gpg-backup
@@ -1,6 +1,11 @@
 #!/bin/sh
 
-BKP_DIR=$(mktemp -d)
+if [ "$(uname)" = "Darwin" ]; then
+	BKP_DIR=$(mktemp -d -t tmp)
+else
+	BKP_DIR=$(mktemp -d)
+fi
+
 FILES=$BKP_DIR/gpg-files
 mkdir $FILES
 cp ~/.gnupg/pubring.gpg $FILES
@@ -16,6 +21,10 @@ openssl enc \
 	-${etype} \
 	-in $BKP_DIR/gpg.tar.bz2 \
 	-out $out
+if [ $? -ne 0 ]; then
+	echo "failed to encrypt"
+	exit 1
+fi
 
 cd $BKP_DIR 
 rm gpg.tar.bz2
diff --git a/sh/gpg-restore b/sh/gpg-restore
--- a/sh/gpg-restore
+++ b/sh/gpg-restore
@@ -7,16 +7,26 @@ fi
 
 etype=aes-256-cbc
 
-TMP_DIR=$(mktemp -d)
+if [ "$(uname)" = "Darwin" ]; then
+	TMP_DIR=$(mktemp -d -t tmp)
+else
+	TMP_DIR=$(mktemp -d)
+fi
+
 openssl enc \
 	-d -${etype} \
 	-in $1 \
 	-out $TMP_DIR/gpg.tar.bz2
+if [ $? -ne 0 ]; then
+	echo "failed to decrypt"
+	exit 1
+fi
 
 cd $TMP_DIR
 tar -xjvf gpg.tar.bz2
 cd gpg-files
 
+mkdir -p $HOME/.gnupg/
 cp pubring.gpg $HOME/.gnupg/
 cp secring.gpg $HOME/.gnupg/
 gpg --import-ownertrust ownertrust-gpg.txt
